version: "3.7"
services:
  api:
    image: "marquezproject/marquez:${TAG}"
    container_name: marquez-api
    environment:
      - MARQUEZ_PORT=${API_PORT}
      - MARQUEZ_ADMIN_PORT=${API_ADMIN_PORT}
    ports:
      - "${API_PORT}:${API_PORT}"
      - "${API_ADMIN_PORT}:${API_ADMIN_PORT}"
    volumes:
      - data:/opt/marquez
    links:
      - "db:postgres"
    depends_on:
      - db
    entrypoint: 
      - /opt/marquez/wait-for-it.sh 
      - db:${POSTGRES_PORT}
      - --
      - ./entrypoint.sh

  db:
    image: postgres:14
    container_name: marquez-db
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - MARQUEZ_DB=marquez
      - MARQUEZ_USER=marquez
      - MARQUEZ_PASSWORD=marquez
    volumes:
      - db-conf:/etc/postgresql
      - db-init:/docker-entrypoint-initdb.d
      - db-backup:/var/lib/postgresql/data
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    # Enables SQL statement logging (see: https://www.postgresql.org/docs/12/runtime-config-logging.html#GUC-LOG-STATEMENT)
    # command: ["postgres", "-c", "log_statement=all"]
  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file: ./.env
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./OpenLineage_App/docker/database:/docker-entrypoint-initdb.d/

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
      interval: 20s
      timeout: 20s
      retries: 5
    restart: always

  springboot:
      image: openlineage_java_app
      container_name: springboot
      env_file: ./.env
      environment:
        MYSQL_DATABASE: ${DATABASE_NAME}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASSSWORD}
      ports:
        - "8080:8080"
      depends_on:
        mysql:
          condition: service_healthy

volumes:
  data:
  db-conf:
  db-init:
  db-backup:
  mysql_data:
