version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file: ./.env
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./OpemLineage_App/docker/database:/docker-entrypoint-initdb.d/

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
      interval: 20s
      timeout: 20s
      retries: 5
    restart: always

  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot
    env_file: ./.env
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSSWORD}
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
    mysql_data:
